data_pack:
  load: .
  min_format: [121,0]
  max_format: [121,0]
  pack_format: 121

resource_pack:
  load: .
  min_format: [97,1]
  max_format: [97,1]
  pack_format: 97

pipeline:
  - mecha

"description": [
  {"text":"\ud83d\udd25 Hero's Journey \ud83d\udd25", "color":"#e079fa"},
  {"text":"\n"},
  {"text":"A journey to The End","color":"#7e7e7e"}
]